### PR TITLE
Cooperate with InternalHeaters

### PR DESCRIPTION
**Pull request by janxious**
I added a feature to a mod of mine, InternalHeaters, to key engine heat to be double dissipation if  DHS were present exclusively on a mech. This is to deal with a few issues with the royal mechs (story highlander, BK, and atlas) that had really weird heat and fit because engines weren't modeled.

Requires https://github.com/janxious/InternalHeaters/releases/tag/v0.0.8 or above to work properly.

Note the "(DHS Engine)" here. 
screen shot 2018-06-13 at 12 23 37 pm

----

I'm still trying to track down how the little orange bits are drawn on screen to fix that, too.

### CODE REVIEW

**Comment by ACCount12** [comment]
Looks good. I would accept this PR once I'm back to updating this mod.

**Comment by ACCount12** [comment]
As for the orange bits: see https://github.com/CptMoore/StatsFixMod

**Comment by ACCount12** [comment]
Hm. Your mod considers a 0 heat sinks mech to be full DHS. It also considers heat banks and exchangers regular heat sinks. I enjoy having my thermal efficiency boosted on most of my tight builds, but I'm sure that's not intended behavior.

**Comment by janxious** [comment]
For the purposes of this, heat banks and exchangers are considered to be singles (which I believe came up in discord). I could add it as an option to Internal Heaters, but for now I'm going to punt. If you feel strongly you want that option before merging, then I will do it. There is a fix for the zero heatsinks double heat sink output here: https://github.com/janxious/InternalHeaters/releases/tag/v0.0.9

**Comment by ACCount12** [comment]
I tweaked your code a bit and added it. It supports InternalHeaters as of v1.2 release.

**Pull request closed without merging**
